# Generated by Django 5.1.7 on 2025-03-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancesession',
            name='email',
            field=models.EmailField(default='nayakjhunu40@gmail.com', max_length=254),
        ),
    ]
